spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///springboot?serverTimezone=UTC
      username: root
      password: 2410
#  elasticsearch:
#    rest:
#      uris: http://localhost:9200

  elasticsearch:
    uris: http://localhost:9200

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

