server:
  port: 80

logging:
  level:
    root: info


country: hubei

user:
  name: xiaowen
  age: 24


likes:
  - game
  - swimming
  - sing


baseDir: c:\windows
# 使用${属性名}引用数据
tempDir: ${baseDir}\temp


datasource:
  driver: com.mysql.jdbc.driver
  url: jdbc:mysql:///springboot
  username: root
  password: 2410
